---
apiVersion: v1
kind: Secret
metadata:
  name: var-system-domain
type: Opaque
stringData:
  value: foo.com
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-manifest
data:
  manifest: |
    ---
    name: nats-deployment
    releases:
    - name: nats
      version: "26"
      url: docker.io/cfcontainerization
      stemcell:
        os: opensuse-42.3
        version: 30.g9c91e77-30.80-7.0.0_257.gb97ced55
    instance_groups:
    - name: nats
      instances: 1
      jobs:
      - name: nats
        release: nats
        properties:
          nats:
            user: admin
            password: ((nats_password))
            cert: ((nats_cert))
    variables:
    - name: nats_password
      type: password
    - name: nats_ca
      type: certificate
      options:
        is_ca: true
        common_name: routerCA
    - name: nats_cert
      type: certificate
      options:
        ca: nats_ca
        common_name: routerSSL
        alternative_names:
        - "((system_domain))"
        - "*.((system_domain))"

---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: BOSHDeployment
metadata:
  name: nats-deployment
spec:
  manifest:
    name: nats-manifest
    type: configmap
