---
apiVersion: v1
kind: Secret
metadata:
  name: var-custom-password
type: Opaque
stringData:
  password: custom_password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-manifest
data:
  manifest: |
    ---
    name: nats-deployment
    releases:
    - name: nats
      version: "26"
      url: docker.io/cfcontainerization
      stemcell:
        os: opensuse-42.3
        version: 30.g9c91e77-30.80-7.0.0_257.gb97ced55
    instance_groups:
    - name: nats
      instances: 1
      jobs:
      - name: nats
        release: nats
        properties:
          nats:
            user: admin
            password: ((custom_password))
      env:
        bosh:
          agent:
            settings:
              disable_log_sidecar: true
    variables:
    - name: custom_password
      type: password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ops-scale
data:
  ops: |
    - type: replace
      path: /instance_groups/name=nats?/instances
      value: 2
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: BOSHDeployment
metadata:
  name: nats-deployment
spec:
  manifest:
    name: nats-manifest
    type: configmap
  ops:
  - name: ops-scale
    type: configmap
