apiVersion: apps/v1
kind: Deployment
metadata:
  name: entangled-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      example: owned-by-dpl
  template:
    metadata:
      annotations:
        quarks.cloudfoundry.org/consumes: '[{"name":"nats","type":"nats"}]'
        quarks.cloudfoundry.org/deployment: nats-deployment
      labels:
        example: owned-by-dpl
      name: entangled
    spec:
      containers:
      - command:
        - sleep
        - "3600"
        image: busybox
        imagePullPolicy: Always
        name: busybox
      restartPolicy: Always
      terminationGracePeriodSeconds: 1
