---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ops-password
data:
  ops: |
    - type: replace
      path: /instance_groups/name=nats?/jobs/name=nats/properties/nats/password
      value: qwerty1234
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: BOSHDeployment
metadata:
  name: nats-deployment
spec:
  manifest:
    name: nats-manifest
    type: secret
  ops:
  - name: ops-password
    type: configmap
