apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksStatefulSet
metadata:
  name: example-quarks-statefulset
spec:
  template:
    metadata:
      labels:
        app: example-statefulset
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: example-statefulset
        spec:
          containers:
          - name: busybox
            image: busybox
            command:
            - sleep
            - "3600"
          tolerations:
          - key: "key"
            operator: "Equal"
            value: "value"
            effect: "NoSchedule"
