apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksStatefulSet
metadata:
  name: example-quarks-statefulset
spec:
  zones: ["dal10", "dal13"]
  updateOnConfigChange: true
  template:
    metadata:
      labels:
        app: example-statefulset
    spec:
      replicas: 2
      template:
        metadata:
          labels:
            app: example-statefulset
        spec:
          containers:
          - name: busybox
            image: busybox
            command:
            - sleep
            - "3600"
