apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksStatefulSet
metadata:
  name: example-quarks-statefulset
spec:
  updateOnConfigChange: true
  template:
    metadata:
      annotations:
        "quarks.cloudfoundry.org/canary-rollout-enabled": "true"
        "quarks.cloudfoundry.org/update-watch-time-ms": "120000"
        "quarks.cloudfoundry.org/canary-watch-time-ms": "120000"
      labels:
        app: example-statefulset
    spec:
      replicas: 2
      template:
        metadata:
          labels:
            app: example-statefulset
        spec:
          volumes:
          - name: secret1-volume
            secret:
              secretName: example1
          containers:
          - name: busybox
            image: busybox
            command:
            - "false"
            volumeMounts:
              - name: secret1-volume
                readOnly: true
                mountPath: "/etc/secret1-volume"
            env:
              - name: SPECIAL_KEY
                valueFrom:
                  configMapKeyRef:
                    name: example1
                    key: key1
